### ISSUE TITLE
Support for PNFs and CNFs

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-schema#79]
Physical Network Functions
Cloud Native Network Functions (Kubernets)
(optional) Hybrid Network Functions

Implemented through PDUs and CNDUs (see mail thread):

- xNFD has VDU(s) ==> VNF 
- xNFD has PDU(s) ==> PNF
- xNFD has CNDU(s) ==> CNNF
- xNFD has VDU(s), PDUs, CNDUs ==> HNF (not saying that we should try to deploy something this complicated :-D but the concept makes sense and we can easily built it into the schemas)

Final design to be made in Detmold F2F. Done.

TODOs

- [x] Create [wiki page with an example for a PNF](https://github.com/sonata-nfv/tng-schema/wiki/PNF-VNFD-Example) to collect inputs about the field/parameters needed in a PDU (similar to the [CNF example](https://github.com/sonata-nfv/tng-schema/wiki/CNF-VNFD-Example)) -> maybe links are enough?
- [X] Allow CNF and PNF objects in vnfd-schema, ensure that at **least one** of them is always there
- [x] Create example PNF in tng-schema
- [x] Create example CNF in tng-schema
- [x] Create example HNF in tng-schema
- [x] Finalize CNDU schema
- [x] Finalize PNF schema
- [x] update release notes for 4.1

**Comment by mpeuster** [comment]
Development done in: https://github.com/mpeuster/tng-schema/tree/feature-79

**Comment by stefanbschneider** [comment]
Do we also need to update the schema for [xNF records](https://github.com/sonata-nfv/tng-schema/blob/master/function-record/vnfr-schema.yml)?

**Comment by mpeuster** [comment]
I think so. But I would assume that this is something for the WP5 guys. They know what runtime infos they want to store in the SP's repos. Heavily depends on the implementation.

Not even sure, if the SP validates against the record schemas at all :-)

**Comment by stefanbschneider** [comment]
As it seems like we don't have any PNFs in our vertical pilots, we agreed on finishing the work on PDUs in the schemas (so that we can support them conceptually), but don't implement anything in the SP for now.

Remaining steps:
- [x] _Stefan_: Provide an updated, refactored example of a VNFD with a PDU and annotations about which fields are mandatory and which are optional: [here](https://github.com/sonata-nfv/tng-schema/wiki/PNF-VNFD-Example#refactored-clean-version)
- [ ] _Others_: Provide feedback, update the example if necessary
- [x] _Stefan_: Once example is stable, implement the changes in the schemas
